version: '3.8'

name: boboweike

services:
  postgres:
    image: postgres:14-alpine
    container_name: boboweike-db
    restart: always
    volumes:
      - boboweike-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: boboweike
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'dev', '-d', 'boboweike']
      interval: 10s
      timeout: 20s
      retries: 5
    ports:
      - 5432:5432

volumes:
  boboweike-data:
