version: '3.8'

name: boboweike

services:
  postgres:
    image: postgres:14-alpine
    container_name: boboweike-db
    restart: always
    volumes:
      - boboweike-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: bobo
      POSTGRES_PASSWORD: dev-pass
      POSTGRES_DB: boboweike-db
    ports:
      - 5432:5432

volumes:
  boboweike-data:
